# Generated by Django 5.2.4 on 2025-08-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('sector', models.CharField(max_length=100)),
                ('sub_sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('incorporation_date', models.DateField()),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('frequency', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Semi-Annual', 'Semi-Annual'), ('Annual', 'Annual')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Offboarded', 'Offboarded')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
