# Generated by Django 5.2.4 on 2025-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('SaaS', 'SaaS'), ('Fintech', 'Fintech'), ('Biotech', 'Biotech'), ('E-commerce', 'E-commerce'), ('Healthcare', 'Healthcare'), ('EdTech', 'EdTech'), ('AI/ML', 'AI/ML'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='sub_sector',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('DeFi', 'DeFi'), ('InsurTech', 'InsurTech'), ('Telemedicine', 'Telemedicine'), ('Marketplace', 'Marketplace'), ('Other', 'Other')], max_length=50),
        ),
    ]
